# Generated by Django 6.0.3 on 2026-04-03 17:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='rating_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='tracking_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
